#!/bin/bash
# openhost-tangled first-boot / every-boot init.
#
# Responsibilities:
#   1. Compute the knot's public HOSTNAME from the OpenHost zone
#      ($OPENHOST_APP_NAME.$OPENHOST_ZONE_DOMAIN, e.g.
#      tangled.andrew-1.selfhost.imbue.com).  The knot bakes this into
#      federation records and git-remote hints, so it must be the real
#      public host.
#   2. Validate that the operator supplied their ATProto owner DID
#      (KNOT_OWNER_DID).  The knot refuses to start without an owner,
#      and it can't be auto-generated — it's the operator's identity.
#   3. Lay out persistent state under $OPENHOST_APP_DATA_DIR:
#        repositories/  — bare git repos (the durable data)
#        knotserver.db  — knot metadata (members, keys, oplog cursor)
#        keys/          — sshd host keys (stable across restarts)
#      and generate sshd host keys on first boot.
#   4. Write /etc/environment-openhost-tangled with the resolved
#      KNOT_* env vars for start.sh to source.
#
# This does not fail the container if the owner DID is missing; instead
# it writes a sentinel so the auth_proxy can serve a clear "set your
# owner DID" setup page, and the knot is left unstarted (start.sh
# checks the sentinel).  That gives the operator an actionable message
# instead of a crash loop.

set -euo pipefail

PERSIST="${OPENHOST_APP_DATA_DIR:-/data/app_data/tangled}"
APP_NAME="${OPENHOST_APP_NAME:-tangled}"
ZONE_DOMAIN="${OPENHOST_ZONE_DOMAIN:-localhost}"

REPO_DIR="$PERSIST/repositories"
DB_PATH="$PERSIST/knotserver.db"
KEYS_DIR="$PERSIST/keys"
ENV_FILE=/etc/environment-openhost-tangled
SENTINEL_NO_OWNER="$PERSIST/.needs-owner-did"

KNOT_HOSTNAME="${APP_NAME}.${ZONE_DOMAIN}"

# Inherit the platform owner's username from OpenHost.  The router
# injects OPENHOST_OWNER_USERNAME (the compute-space owner's chosen
# name, defaulting to "owner").  We use it to personalize the
# SSO-gated setup page and as the knot's default git author identity,
# so the owner's platform identity flows through instead of a generic
# placeholder.
OWNER_USERNAME="${OPENHOST_OWNER_USERNAME:-owner}"

mkdir -p "$REPO_DIR" "$KEYS_DIR"
# The knot runs as the git user; it must own its data.
chown -R git:git "$REPO_DIR" "$PERSIST" 2>/dev/null || true

# ----------------------------------------------------------------------
# Owner DID
# ----------------------------------------------------------------------
# The knot's owner is an ATProto DID.  OpenHost has no user-env-var
# mechanism, so we source the DID, in priority order, from:
#   1. KNOT_OWNER_DID / KNOT_SERVER_OWNER / OWNER env (if a future
#      OpenHost version or a manual deploy provides one), else
#   2. the persisted owner-did file that the auth_proxy writes when the
#      owner submits it through the setup form at the app URL.
# This makes the normal flow "deploy → open app → paste your DID".
OWNER_DID_FILE="$PERSIST/owner-did"
OWNER_DID="${KNOT_OWNER_DID:-${KNOT_SERVER_OWNER:-${OWNER:-}}}"

if [[ -z "$OWNER_DID" && -f "$OWNER_DID_FILE" ]]; then
    OWNER_DID="$(head -n1 "$OWNER_DID_FILE" | tr -d '[:space:]')"
fi

rm -f "$SENTINEL_NO_OWNER"
if [[ -z "$OWNER_DID" || ! "$OWNER_DID" =~ ^did: ]]; then
    echo "[openhost-init] WARNING: KNOT_OWNER_DID is not set to a valid DID (got: '${OWNER_DID}')."
    echo "[openhost-init] The knot will not start until you set KNOT_OWNER_DID to your ATProto DID."
    : > "$SENTINEL_NO_OWNER"
fi

# ----------------------------------------------------------------------
# sshd host keys (first boot only), on the persistent volume
# ----------------------------------------------------------------------
[[ -f "$KEYS_DIR/ssh_host_rsa_key" ]]     || ssh-keygen -t rsa     -f "$KEYS_DIR/ssh_host_rsa_key"     -q -N ""
[[ -f "$KEYS_DIR/ssh_host_ecdsa_key" ]]   || ssh-keygen -t ecdsa   -f "$KEYS_DIR/ssh_host_ecdsa_key"   -q -N ""
[[ -f "$KEYS_DIR/ssh_host_ed25519_key" ]] || ssh-keygen -t ed25519 -f "$KEYS_DIR/ssh_host_ed25519_key" -q -N ""
# sshd's config references /etc/ssh/keys; symlink to the persistent dir.
mkdir -p /etc/ssh/keys
for k in ssh_host_rsa_key ssh_host_ecdsa_key ssh_host_ed25519_key; do
    ln -sf "$KEYS_DIR/$k" "/etc/ssh/keys/$k"
    ln -sf "$KEYS_DIR/$k.pub" "/etc/ssh/keys/$k.pub" 2>/dev/null || true
done
chmod 600 "$KEYS_DIR"/ssh_host_* 2>/dev/null || true

# sshd needs a privilege-separation dir.
mkdir -p /var/empty /run/sshd

# ----------------------------------------------------------------------
# Env file for start.sh
# ----------------------------------------------------------------------
cat > "$ENV_FILE" <<EOF
# Generated by openhost-init.sh; sourced by start.sh.  Do not edit.
export KNOT_SERVER_HOSTNAME='${KNOT_HOSTNAME}'
export KNOT_SERVER_OWNER='${OWNER_DID}'
export KNOT_SERVER_LISTEN_ADDR='127.0.0.1:5555'
export KNOT_SERVER_INTERNAL_LISTEN_ADDR='127.0.0.1:5444'
export KNOT_SERVER_DB_PATH='${DB_PATH}'
export KNOT_REPO_SCAN_PATH='${REPO_DIR}'
export APPVIEW_ENDPOINT='${KNOT_APPVIEW_ENDPOINT:-https://tangled.org}'
# The knot uses these as the default git author/committer identity for
# server-side operations (e.g. merge commits it creates), inheriting
# the platform owner's username.
export KNOT_GIT_USER_NAME='${OWNER_USERNAME}'
export KNOT_GIT_USER_EMAIL='${OWNER_USERNAME}@${KNOT_HOSTNAME}'
export OPENHOST_TANGLED_SENTINEL_NO_OWNER='${SENTINEL_NO_OWNER}'
export OPENHOST_TANGLED_HOSTNAME='${KNOT_HOSTNAME}'
export OPENHOST_TANGLED_OWNER_DID_FILE='${OWNER_DID_FILE}'
export OPENHOST_TANGLED_OWNER_USERNAME='${OWNER_USERNAME}'
EOF
chmod 0644 "$ENV_FILE"

echo "[openhost-init] KNOT hostname: ${KNOT_HOSTNAME}"
echo "[openhost-init] owner DID:     ${OWNER_DID:-<unset>}"
echo "[openhost-init] repo dir:      ${REPO_DIR}"
echo "[openhost-init] appview:       ${KNOT_APPVIEW_ENDPOINT:-https://tangled.org}"
echo "[openhost-init] done"
